modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]

modId="riskofrain_items"
version="1.0"
displayName="Risk of Rain Items"
logoFile="logo.png"
credits="Thanks everyone who supports the effort and HOPOO GAMES for providing us with such a universe."
authors="Colo Champre"

description='''
This mod brings some content from the Risk of Rain universe into Minecraft!
'''
